import { renderScores, assessmentEditor } from './scores.js';
import { request, clearSession } from './http.js';
const API = window.GEOCREDIT_API_URL ?? window.location.origin;
const $ = id => document.getElementById(id);
let token = localStorage.getItem('geocredit.token') ?? '', reviewApplication = null, reviewerRole = localStorage.getItem('geocredit.role') ?? '';
let cdoCustomers = [], cdoCustomer = null, cdoApplication = null, cdoMediaId = '';
const headers = () => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });
const money = value => `BDT ${Number(value ?? 0).toLocaleString('en-BD', { maximumFractionDigits: 0 })}`;
const requestKey = () => `web-${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function api(path, options = {}) { return request(API, token, path, options); }
function show(id, visible = true) { $(id).classList.toggle('hidden', !visible); }
function message(id, text, good = false) { $(id).textContent = text; $(id).className = `message ${good ? 'ok' : ''}`; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[ch])); }
function memberLabel(item) { const c = item.customer ?? {}; return { ref: c.customerRef ?? item.customerRef ?? 'Customer reference unavailable', name: c.displayName ?? item.customerName ?? 'Customer name unavailable' }; }

$('loginBtn').onclick = async () => { try { const result = await api('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ username: $('username').value }) }); token = result.token; reviewerRole = result.user.role; localStorage.setItem('geocredit.token',token); localStorage.setItem('geocredit.role',reviewerRole); $('statusPill').textContent = 'Signed in'; $('statusPill').className = 'pill ok'; $('reviewerLabel').textContent = `${result.user.username} · ${result.user.role}`; show('loginCard', false); if (['BM', 'AM', 'RM', 'ADMIN'].includes(reviewerRole)) { show('reviewerCard'); await loadInbox(); } else { show('appCard'); await loadCdoCustomers(); } } catch (e) { message('loginMessage', e.message); } };

async function loadInbox() { try { const inbox = await api('/api/v1/review/inbox'); inbox.sort((a, b) => (a.customer?.customerRef ?? '').includes('DEMO') ? -1 : (b.customer?.customerRef ?? '').includes('DEMO') ? 1 : 0); const list = $('inboxList'); $('inboxSelect').innerHTML = inbox.map(item => `<option value="${item.id}">${escapeHtml(memberLabel(item).ref)}</option>`).join(''); list.innerHTML = inbox.length ? inbox.map(item => { const c = memberLabel(item); return `<button type="button" class="memberCard" data-application-id="${item.id}"><strong>${escapeHtml(c.name)}</strong><span>${escapeHtml(c.ref)}</span><small>${escapeHtml(item.product)} · ${escapeHtml(item.status)} · v${item.version}</small><b>VIEW DETAILS ›</b></button>`; }).join('') : '<p class="muted">No applications awaiting review.</p>'; list.querySelectorAll('[data-application-id]').forEach(card => { card.onclick = () => { localStorage.setItem('geocredit.returnUrl', window.location.href); window.location.href = `review.html?id=${encodeURIComponent(card.dataset.applicationId)}`; }; }); show('reviewDetail', false); show('inboxList', true); } catch (e) { message('reviewMessage', e.message); } }

async function loadReview(id) { if (!id) return; try { reviewApplication = await api(`/api/v1/applications/${id}`); const area = await api(`/api/v1/applications/${id}/area-intelligence`).catch(() => reviewApplication.areaIntelligence); const timeline = await api(`/api/v1/applications/${id}/timeline`).catch(() => []); const c = reviewApplication.customer ?? {}; $('reviewStatus').textContent = reviewApplication.status; $('reviewVersion').textContent = `v${reviewApplication.version}`; $('reviewIdentity').innerHTML = `<strong>Member image</strong><br>${c.imageUrl ? `<img class="memberImage" src="${escapeHtml(c.imageUrl)}" alt="Member image">` : '<span class="muted">Image unavailable</span>'}<br><strong>Application ID</strong>: ${escapeHtml(reviewApplication.id)}<br><strong>Customer ID</strong>: ${escapeHtml(reviewApplication.customerId)}<br><strong>Member Name</strong>: ${escapeHtml(c.displayName ?? 'Unavailable')}<br><strong>NID</strong>: ${escapeHtml(c.nid ?? 'Unavailable')}<br><strong>DOB</strong>: ${(c.dateOfBirth ?? '').slice(0, 10).replaceAll('-', ':') || 'Unavailable'}<br><strong>VO Code</strong>: ${escapeHtml(c.voCode ?? 'Unavailable')}<br><strong>ERP Member ID</strong>: ${escapeHtml(c.erpMemberId ?? 'Unavailable')}`; const f = reviewApplication.financialAssessment; $('reviewFinancial').innerHTML = f ? `<strong>Financial assessment</strong><br>Proposed amount: ${money(f.proposedAmount)} · Income: ${money(f.monthlyIncome)} · Expense: ${money(f.monthlyExpense)} · Term: ${f.proposedTermMonths} months · Installment: ${money(f.proposedInstallment)} · Surplus: ${money(f.monthlySurplus)}` : 'Financial assessment not available.'; const risk = reviewApplication.riskAssessment; $('reviewRisk').innerHTML = renderScores(reviewApplication.assessments); const metrics = area?.metrics ?? reviewApplication.areaIntelligence?.metrics ?? {}; $('reviewArea').innerHTML = `<strong>Area intelligence</strong><br>Area Credit Score: ${metrics.areaCreditScore ?? 'UNAVAILABLE'} / 100 · Outcome: ${escapeHtml(area?.outcome ?? reviewApplication.areaIntelligence?.outcome ?? 'UNAVAILABLE')} · Borrowers: ${metrics.borrowerCount ?? 'N/A'} · Overdue: ${metrics.overdueCount ?? 'N/A'}`; $('reviewTimeline').innerHTML = `Timeline: ${timeline.length} recorded workflow action${timeline.length === 1 ? '' : 's'}.`; const actions = { [reviewerRole]: reviewApplication.allowedActions ?? [] }; $('reviewAction').innerHTML = '<option value="">Choose action...</option>' + (actions[reviewerRole] ?? []).map(action => `<option value="${action}">${action.replaceAll('_', ' ')}</option>`).join(''); show('inboxList', false); show('reviewDetail', true); } catch (e) { message('reviewMessage', e.message); } }

$('backToInboxBtn').onclick = () => { show('reviewDetail', false); show('inboxList', true); };
$('refreshInboxBtn').onclick = () => loadInbox();
$('inboxSelect').onchange = () => loadReview($('inboxSelect').value);
$('saveChecklistBtn').onclick = async () => { try { await api(`/api/v1/applications/${reviewApplication.id}/checklists`, { method: 'PUT', headers: {'If-Match': String(reviewApplication.version)}, body: JSON.stringify({ checklistType: reviewerRole, items: [], remarks: $('checklistRemarks').value }) }); message('reviewMessage', 'Checklist saved.', true); } catch (e) { message('reviewMessage', e.message); } };
$('reviewActionBtn').onclick = async () => { try { const action = $('reviewAction').value; if (!action) throw new Error('Choose a review action'); if (['RETURN', 'REJECT'].includes(action) && !$('checklistRemarks').value.trim()) throw new Error('Remarks are required for sendback and reject.'); if(['APPROVE','REJECT'].includes(action)&&!window.confirm(action+' application '+reviewApplication.id+'?'))return; const result = await api(`/api/v1/applications/${reviewApplication.id}/transitions`, { method: 'POST', headers: { 'Idempotency-Key': requestKey(), 'If-Match': String(reviewApplication.version) }, body: JSON.stringify({ action, confirmed: ['APPROVE','REJECT'].includes(action), remarks: $('checklistRemarks').value.trim() || undefined }) }); message('reviewMessage', `Action applied: ${result.currentStatus}, version ${result.version}.`, true); await loadInbox(); } catch (e) { message('reviewMessage', e.message); } };
const logoutBtn = document.createElement('button'); logoutBtn.textContent = 'Log out'; logoutBtn.className = 'secondary hidden'; document.querySelector('header').append(logoutBtn);
setInterval(() => { logoutBtn.classList.toggle('hidden', !token); }, 250);
logoutBtn.onclick = () => { clearSession(); cdoCustomers=[]; cdoCustomer=null; cdoApplication=null; cdoMediaId=''; document.querySelectorAll('input,textarea').forEach(el=>{el.value='';}); token = ''; reviewApplication = null; reviewerRole = ''; show('loginCard', true); show('appCard', false); show('reviewerCard', false); show('reviewDetail', false); show('inboxList', false); $('username').value = 'cdo.demo'; $('statusPill').textContent = 'Signed out'; $('statusPill').className = 'pill'; message('loginMessage', ''); };

const cdoDetails = document.createElement('div'); cdoDetails.className = 'result hidden'; $('customerSelect').parentElement.after(cdoDetails);
const cdoList = document.createElement('div'); cdoList.className = 'memberList'; $('customerSelect').parentElement.before(cdoList); $('customerSelect').parentElement.classList.add('hidden');
const cdoPageNav = document.createElement('div'); cdoPageNav.className = 'row'; $('appCard').prepend(cdoPageNav);
const cdoStepOne = [...document.querySelectorAll('#appCard > .sectionTitle, #appCard > .grid, #appCard > #draftBtn, #appCard > #draftMessage')];
function cdoPage(page) { cdoList.classList.toggle('hidden', page !== 'list'); cdoDetails.classList.toggle('hidden', page !== 'details'); $('workflow').classList.toggle('hidden', page !== 'evidence'); $('areaSection').classList.toggle('hidden', page !== 'area'); $('submitSection').classList.toggle('hidden', page !== 'financial' && page !== 'done'); cdoStepOne.forEach(el => el.classList.toggle('hidden', !['list', 'details'].includes(page))); cdoPageNav.innerHTML = ''; if (page === 'details') { const b = document.createElement('button'); b.className = 'secondary'; b.textContent = '‹ Back to member list'; b.onclick = () => cdoPage('list'); cdoPageNav.append(b); } if (page === 'evidence') { const b = document.createElement('button'); b.className = 'secondary'; b.textContent = '‹ Back to member details'; b.onclick = () => cdoPage('details'); cdoPageNav.append(b); } if (page === 'area') { const b = document.createElement('button'); b.className = 'secondary'; b.textContent = '‹ Back to evidence'; b.onclick = () => cdoPage('evidence'); cdoPageNav.append(b); } if (page === 'financial' || page === 'done') { const b = document.createElement('button'); b.className = 'secondary'; b.textContent = '‹ Back to area score'; b.onclick = () => cdoPage('area'); cdoPageNav.append(b); } }
async function loadCdoCustomers() { cdoCustomers = await api('/api/v1/customers'); $('customerSelect').innerHTML = '<option value="">Choose member...</option>' + cdoCustomers.map(c => `<option value="${escapeHtml(c.id)}">${escapeHtml(c.customerRef)} · ${escapeHtml(c.displayName)}</option>`).join(''); $('userLabel').textContent = `${cdoCustomers.length} member(s) available`; $('customerSelect').onchange = () => selectCdoCustomer($('customerSelect').value); cdoPage('list'); }
async function selectCdoCustomer(id) { if (!id) { cdoCustomer = null; cdoDetails.classList.add('hidden'); return; } cdoCustomer = await api(`/api/v1/customers/${id}`); const r = cdoCustomer.riskProfile ?? {}; const s = cdoCustomer.repaymentSummary ?? {}; cdoDetails.innerHTML = `<strong>Member details</strong><br><strong>Member name:</strong> ${escapeHtml(cdoCustomer.displayName)}<br><strong>NID:</strong> ${escapeHtml(cdoCustomer.nid ?? 'Unavailable')}<br><strong>DOB:</strong> ${escapeHtml((cdoCustomer.dateOfBirth ?? '').slice(0,10).replaceAll('-', ':') || 'Unavailable')}<br><strong>VO Code:</strong> ${escapeHtml(cdoCustomer.voCode ?? 'Unavailable')}<br><strong>ERP Member ID:</strong> ${escapeHtml(cdoCustomer.erpMemberId ?? 'Unavailable')}<br><strong>Risk level:</strong> ${escapeHtml(r.riskLevel ?? 'Unavailable')}<br><strong>Current overdue:</strong> ${r.hasCurrentOverdue ? 'Yes' : 'No'}<br><strong>Missed schedule:</strong> ${escapeHtml(s.missedScheduleCount ?? '0')}<br><strong>Overdue amount:</strong> ${money(s.overdueAmount)}${cdoCustomer.imageUrl ? `<br><img class="memberImage" src="${escapeHtml(cdoCustomer.imageUrl)}" alt="Member image">` : ''}`; cdoDetails.classList.remove('hidden'); }
$('draftBtn').onclick = async () => { try { if (!cdoCustomer) throw Error('Select a member first'); const out = await api('/api/v1/applications', { method: 'POST', body: { customerId: cdoCustomer.id, branchId: cdoCustomer.branchId, areaId: cdoCustomer.areaId, regionId: cdoCustomer.regionId, product: 'DABI' } }); cdoApplication = out; $('versionLabel').textContent = `Version ${out.version}`; cdoPage('evidence'); message('draftMessage', 'Draft created. Continue with evidence and GPS.', true); } catch (e) { message('draftMessage', e.message); } };
$('uploadBtn').onclick = async () => { try { if (!cdoApplication) throw Error('Create a draft first'); const file = $('evidenceFile').files[0]; if (!file) throw Error('Choose an evidence image first'); const session = await api('/api/v1/media/s3-upload-sessions', { method: 'POST', body: { mediaType: 'HOUSE' } }); const upload = await fetch(session.uploadUrl, { method: session.method, headers: session.requiredHeaders, body: file }); if (!upload.ok) throw Error(`Private media upload failed (${upload.status})`); await api(`/api/v1/media/${session.mediaId}/s3-complete`, { method: 'POST', headers: { 'X-Upload-Token': session.uploadToken } }); cdoMediaId = session.mediaId; $('uploadSummary').textContent = 'Private evidence uploaded.'; } catch (e) { $('uploadSummary').textContent = e.message; } };
$('geoBtn').onclick = async () => { try { if (!cdoApplication || !cdoMediaId) throw Error('Upload house evidence first'); const pos = await new Promise((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 15000 })); const out = await api(`/api/v1/applications/${cdoApplication.id}/geo-verification`, { method: 'POST', body: { mediaId: cdoMediaId, latitude: pos.coords.latitude, longitude: pos.coords.longitude, accuracyMeters: pos.coords.accuracy ?? 9999, capturedAt: new Date().toISOString() }, headers: { 'If-Match': String(cdoApplication.version) } }); if (out.status !== 'VALID') throw Error(`Server rejected GPS accuracy of ${Math.round(out.accuracyMeters)}m.`); cdoApplication.version = out.version; $('geoSummary').textContent = `Verified (${Math.round(out.accuracyMeters)}m)`; $('geoResult').textContent = 'GPS verified by server.'; cdoPage('area'); } catch (e) { $('geoResult').textContent = e.message; } };
$('areaBtn').onclick = async () => { try { const out = await api(`/api/v1/applications/${cdoApplication.id}/area-intelligence`, { method: 'POST', body: {}, headers: { 'If-Match': String(cdoApplication.version) } }); const score = 'UNVERSIONED'; $('areaPill').textContent = `${score}/100`; $('areaResult').textContent = `${out.outcome} · Area Credit Score: ${score}/100 · ${out.metrics?.borrowerCount ?? 0} nearby borrowers · ${out.metrics?.overdueCount ?? 0} overdue`; cdoPage('financial'); } catch (e) { $('areaResult').textContent = e.message; } };
$('financialBtn').onclick = async () => { try { const out = await api(`/api/v1/applications/${cdoApplication.id}/financial-assessment`, { method: 'PUT', body: { monthlyIncome: Number($('income').value), monthlyExpense: Number($('expense').value), externalDebt: 0, proposedAmount: Number($('amount').value), proposedTermMonths: Number($('term').value) }, headers: { 'If-Match': String(cdoApplication.version) } }); cdoApplication.version = out.version; $('submitResult').textContent = 'Financial assessment saved.';mountCdoAssessment(); } catch (e) { $('submitResult').textContent = e.message; } };
$('submitBtn').onclick = async () => { try { const out = await api(`/api/v1/applications/${cdoApplication.id}/transitions`, { method: 'POST', body: { action: 'SUBMIT' }, headers: { 'If-Match': String(cdoApplication.version), 'Idempotency-Key': requestKey() } }); cdoApplication.version = out.version; $('submitResult').textContent = `Submitted to BM. Status: ${out.currentStatus}`; } catch (e) { $('submitResult').textContent = e.message; } };
const loadCdoCustomersWithList = loadCdoCustomers;
loadCdoCustomers = async () => { await loadCdoCustomersWithList(); cdoList.innerHTML = cdoCustomers.length ? cdoCustomers.map(c => `<button type="button" class="memberCard" data-cdo-id="${escapeHtml(c.id)}"><strong>${escapeHtml(c.displayName)}</strong><span>${escapeHtml(c.customerRef)}</span><small>Customer ID: ${escapeHtml(c.id)}</small><b>VIEW DETAILS ›</b></button>`).join('') : '<p class="muted">No members available.</p>'; cdoList.querySelectorAll('[data-cdo-id]').forEach(card => { card.onclick = async () => { cdoPage('details'); await selectCdoCustomer(card.dataset.cdoId); cdoDetails.insertAdjacentHTML('afterbegin', '<button type="button" class="secondary" id="backToCdoList">‹ Back to member list</button>'); $('backToCdoList').onclick = () => cdoPage('list'); }; }); };
async function restoreSession() { if (token) { try { const me=await api('/api/v1/auth/me'); reviewerRole=me.role; } catch(e) { if(e.status===401) logoutBtn.onclick(); else message('loginMessage',e.message); return; } show('loginCard', false); if (['BM', 'AM', 'RM', 'ADMIN'].includes(reviewerRole)) { show('reviewerCard'); loadInbox(); } else { show('appCard'); loadCdoCustomers(); } }

} restoreSession();

let mutationPending=false;
for(const id of ['loginBtn','draftBtn','uploadBtn','geoBtn','areaBtn','financialBtn','submitBtn','reviewActionBtn','saveChecklistBtn']) {
  const button=$(id),handler=button.onclick;
  button.onclick=async()=>{if(mutationPending)return;mutationPending=true;button.disabled=true;logoutBtn.disabled=true;try{await handler();}finally{button.disabled=false;logoutBtn.disabled=false;mutationPending=false;}};
}

function mountCdoAssessment(){let editor=$('cdoAssessment');if(editor)editor.remove();editor=document.createElement('div');editor.id='cdoAssessment';$('submitSection').append(editor);assessmentEditor(editor,{monthlyIncome:$('income').value,monthlyExpense:$('expense').value},async(input,confirmed)=>{const saved=await api('/api/v1/applications/'+cdoApplication.id+'/assessments/CDO',{method:'PUT',headers:{'If-Match':String(cdoApplication.version)},body:input});cdoApplication.version=saved.version;await api('/api/v1/applications/'+cdoApplication.id+'/checklists',{method:'PUT',headers:{'If-Match':String(saved.version)},body:{checklistType:'CDO',items:['IDENTITY_VERIFIED','EVIDENCE_REVIEWED','FINANCIALS_CONFIRMED'].map(code=>({code,label:code,complete:confirmed}))}});const updated=await api('/api/v1/applications/'+cdoApplication.id);$('submitResult').innerHTML=renderScores(updated.assessments);});}
