const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderScores(bundle){
 const section=(label,assessment)=>`<section><h3>${label}: ${escape(assessment?.result.totalScore??'INCOMPLETE')}</h3><p>${escape(assessment?.result.classification??'INCOMPLETE')} · ${escape(assessment?.result.ruleVersion??'No versioned assessment')}</p>${(assessment?.result.categories??[]).map(c=>`<p>${escape(c.key)}: ${escape(c.score??'INCOMPLETE')} × ${c.weightPercent}% = ${escape(c.weightedContribution??'—')}<br><small>${escape(c.reason)}</small></p>`).join('')}</section>`;
 const canonical=bundle?.canonical?.result??bundle?.cdo?.result??bundle?.bm?.result??{totalScore:'78.42',classification:'LOWER_RISK',ruleVersion:'demo-client-v1',categories:[{key:'incomeSource',score:'82.00',weightPercent:50,weightedContribution:'41.0000',reason:'DEMO_INCOME_STABILITY'},{key:'socialAcceptance',score:'80.00',weightPercent:10,weightedContribution:'8.0000',reason:'DEMO_RATING'},{key:'transactionHistory',score:'75.00',weightPercent:20,weightedContribution:'15.0000',reason:'DEMO_REPAYMENT_HISTORY'},{key:'savings',score:'70.00',weightPercent:10,weightedContribution:'7.0000',reason:'DEMO_SAVINGS_HISTORY'},{key:'houseInfrastructure',score:'74.20',weightPercent:10,weightedContribution:'7.4200',reason:'DEMO_HOUSE_ASSESSMENT'}]}; return `<h2>Client Score · higher is better</h2><p><strong>AI Recommendation — Human Review Required</strong></p>${section('Client Score',{result:canonical})}<p><small>Demo data shown when no complete server assessment is available.</small></p>`;
}

export function assessmentEditor(container,initial,onSave){
 container.innerHTML=`<h3>Scoring assessment (demo)</h3><p>Enter observed facts. Missing fields remain incomplete; portfolio facts come from the server.</p><label>Monthly income BDT<input name="income" inputmode="decimal" value="${escape(initial.monthlyIncome??'')}"></label><label>Monthly expense BDT<input name="expense" inputmode="decimal" value="${escape(initial.monthlyExpense??'')}"></label><label>Monthly external debt payments BDT<input name="debt" inputmode="decimal"></label><label>Social rating 1–10<input name="rating" type="number" min="1" max="10"></label>`;
 for(const [name,label,choices] of [['stability','Income stability',['STABLE','SEASONAL','IRREGULAR']],['structure','House structure',['DURABLE','SEMI_DURABLE','TEMPORARY']],['condition','House condition',['GOOD','FAIR','POOR']],['utilities','Basic utilities',['YES','NO']]]){
   const labelNode=document.createElement('label');labelNode.textContent=label;const select=document.createElement('select');select.name=name;select.innerHTML='<option value="">Not recorded</option>'+choices.map(v=>`<option>${v}</option>`).join('');labelNode.append(select);container.append(labelNode);
 }
 const confirmation=document.createElement('label');confirmation.innerHTML='<input name="confirmed" type="checkbox" style="display:inline-block;width:auto;margin:0 8px 0 0;vertical-align:middle"> I verified identity, reviewed house evidence and confirmed financial information.';container.append(confirmation);
 const button=document.createElement('button');button.textContent='Save assessment and checklist';button.type='button';const message=document.createElement('p');container.append(button,message);
 button.onclick=async()=>{if(button.disabled)return;button.disabled=true;const get=name=>container.querySelector(`[name="${name}"]`).value||undefined;try{await onSave({incomeSource:{monthlyIncome:get('income'),monthlyExpense:get('expense'),monthlyDebtPayment:get('debt'),stability:get('stability')},socialAcceptance:{rating:get('rating')?Number(get('rating')):undefined},houseInfrastructure:{structure:get('structure'),condition:get('condition'),basicUtilities:get('utilities')?get('utilities')==='YES':undefined}},container.querySelector('[name="confirmed"]').checked);message.textContent='Saved. Review scores before proceeding.';}catch(e){message.textContent=e.message;}finally{button.disabled=false;}};
}
