import type { AssessmentInput } from '@geocredit/risk-engine';
import type { AssessmentBundle } from './AssessmentPanel';
import * as FileSystem from 'expo-file-system/legacy';

export type MobileConfig = { apiBaseUrl: string };
export type UploadSession = { mediaId: string; uploadSessionId: string; uploadToken: string; uploadUrl: string; method: 'PUT'; requiredHeaders: Record<string, string>; expiresInSeconds: number; private: boolean };
export type GeoVerificationResult = { status: 'PENDING' | 'VALID' | 'INVALID'; latitude: number; longitude: number; accuracyMeters: number; capturedAt: string };
export type AreaIntelligence = { outcome: string; metrics: { areaCreditScore?: number; borrowerCount: number; overdueCount: number; riskDistribution?: Record<string, number> }; nearbyBorrowers?: Array<{ reference: string; distanceBandMeters: number; riskLevel: string; repaymentSummary: { hasOverdue: boolean; hasRecentDelay: boolean }; mapPoint?: { latitude:number; longitude:number } }> };
export type AuthUser = { id: string; username: string; role: 'CDO' | 'CO' | 'BM' | 'AM' | 'RM' | 'ADMIN' };
export type MemberDetails = { id: string; customerRef: string; displayName: string; nid?: string; dateOfBirth?: string; imageUrl?: string; voCode?: string; erpMemberId?: string; riskProfile: { riskLevel: string; hasCurrentOverdue: boolean; hasRecentDelay: boolean; savingsTrend: string }; repaymentSummary: { overdueAmount: number | string; missedScheduleCount: number }; loans: Array<{ loanRef: string; status: string; outstanding: number | string; overdue: number | string }>; savings: Array<{ balance: number | string }> };
export type ReviewApplication = { assessments?: AssessmentBundle; allowedActions?: string[]; id: string; product: string; customerId: string; status: string; version: number; customer?: { customerRef: string; displayName: string; nid?: string; dateOfBirth?: string; imageUrl?: string; voCode?: string; erpMemberId?: string } | null; financialAssessment?: { monthlyIncome: number | string; monthlyExpense: number | string; proposedAmount: number | string; proposedTermMonths: number | string; monthlySurplus: number | string; proposedInstallment: number | string } | null; riskAssessment?: { affordable: boolean; monthlySurplus: number | string; proposedInstallment: number | string; expenseRatio: number; riskScore?: number; riskBand?: string } | null; areaIntelligence?: AreaIntelligence | null };

export class GeoCreditMobileClient {
  private token = '';
  private retryKeys = new Map<string,string>();
  private application: { id: string; version: number } | null = null;
  constructor(private readonly config: MobileConfig) {}

  async login(username: string) { const result = await this.request<{ token: string; user: AuthUser }>('/api/v1/auth/login', { method: 'POST', body: { username }, anonymous: true }); this.token = result.token; return result.user; }
  logout() { this.retryKeys.clear(); this.token = ''; this.application = null; }
  async getCustomers() { return this.request<Array<{ id: string; customerRef: string; displayName: string; branchId: string; areaId: string; regionId: string }>>('/api/v1/customers'); }
  async getCustomer(customerId: string) { return this.request<MemberDetails>(`/api/v1/customers/${customerId}`); }
  async createDabiDraft(input: { customerId: string; branchId: string; areaId: string; regionId: string }) { const existing=await this.request<Array<{id:string;version:number}>>('/api/v1/applications?customerId='+encodeURIComponent(input.customerId));if(existing[0]){this.application=existing[0];return existing[0];} const result = await this.request<{ id: string; version: number }>('/api/v1/applications', { method: 'POST', body: { ...input, product: 'DABI' } }); this.application = result; return result; }
  async createPrivateUploadSession(mediaType: 'HOUSE' | 'BUSINESS' | 'DOCUMENT' = 'HOUSE') { return this.request<UploadSession>('/api/v1/media/s3-upload-sessions', { method: 'POST', body: { mediaType } }); }
  async uploadEvidence(file: Blob, mediaType: 'HOUSE' | 'BUSINESS' | 'DOCUMENT' = 'HOUSE') { const session = await this.createPrivateUploadSession(mediaType); const upload = await fetch(session.uploadUrl, { method: session.method, headers: session.requiredHeaders, body: file }); if (!upload.ok) throw new Error(`Private media upload failed (${upload.status})`); await this.request(`/api/v1/media/${session.mediaId}/s3-complete`, { method: 'POST', headers: { 'X-Upload-Token': session.uploadToken } }); return session.mediaId; }
  async uploadEvidenceUri(uri: string, mediaType: 'HOUSE' | 'BUSINESS' | 'DOCUMENT' = 'HOUSE') { const session = await this.createPrivateUploadSession(mediaType); const upload = await FileSystem.uploadAsync(session.uploadUrl, uri, { httpMethod: session.method, uploadType: FileSystem.FileSystemUploadType.BINARY_CONTENT, headers: session.requiredHeaders }); if (upload.status < 200 || upload.status >= 300) throw new Error(`Private media upload failed (${upload.status}).`); await this.request(`/api/v1/media/${session.mediaId}/s3-complete`, { method: 'POST', headers: { 'X-Upload-Token': session.uploadToken } }); return session.mediaId; }
  async verifyReviewGeo(id:string,version:number,mediaId:string,capture:{latitude:number;longitude:number;accuracyMeters:number;capturedAt:string}){return this.request<GeoVerificationResult>(`/api/v1/applications/${id}/geo-verification`,{method:'POST',headers:{'If-Match':String(version)},body:{mediaId,...capture}});}
  async verifyGeo(mediaId: string, capture: { latitude: number; longitude: number; accuracyMeters: number; capturedAt: string }) { return this.request<GeoVerificationResult>(`/api/v1/applications/${this.id()}/geo-verification`, { method: 'POST', body: { mediaId, ...capture } }); }
  async getAreaIntelligence() { const result = await this.request<AreaIntelligence>(`/api/v1/applications/${this.id()}/area-intelligence`, { method: 'POST', body: {} }); return result; }
  async saveFinancialAssessment(input: { monthlyIncome: number; monthlyExpense: number; externalDebt: number; proposedAmount: number; proposedTermMonths: number }) { const result = await this.request<{ version: number }>('/api/v1/applications/' + this.id() + '/financial-assessment', { method: 'PUT', body: input }); this.application = { ...this.application!, version: result.version }; return result; }
  async submit() { const result = await this.request<{ version: number; currentStatus: string }>('/api/v1/applications/' + this.id() + '/transitions', { method: 'POST', headers: { 'Idempotency-Key': `mobile-submit-${this.id()}-${Date.now()}` }, body: { action: 'SUBMIT' } }); this.application = { ...this.application!, version: result.version }; return result; }
  async getReviewInbox() { return this.request<ReviewApplication[]>('/api/v1/review/inbox'); }
  async getApplication(applicationId: string) { return this.request<ReviewApplication>(`/api/v1/applications/${applicationId}`); }
  async applyReviewAction(applicationId: string, version: number, action: string, remarks?: string, confirmed = false) { return this.request<{ currentStatus: string; version: number }>(`/api/v1/applications/${applicationId}/transitions`, { method: 'POST', headers: { 'If-Match': String(version), 'Idempotency-Key': `mobile-review-${applicationId}-${action}-${Date.now()}` }, body: { action, remarks, confirmed } }); }
  async getDraftApplication() { const result=await this.getApplication(this.id()); this.application={id:result.id,version:result.version}; return result; }
  async saveRoleAssessment(id:string,version:number,role:'CDO'|'BM',input:AssessmentInput,confirmed:boolean){const saved=await this.request<{version:number}>(`/api/v1/applications/${id}/assessments/${role}`,{method:'PUT',headers:{'If-Match':String(version)},body:input});if(this.application?.id===id)this.application.version=saved.version;await this.request(`/api/v1/applications/${id}/checklists`,{method:'PUT',headers:{'If-Match':String(saved.version)},body:{checklistType:role,items:['IDENTITY_VERIFIED','EVIDENCE_REVIEWED','FINANCIALS_CONFIRMED'].map(code=>({code,label:code,complete:confirmed}))}});return this.getApplication(id);}
  private id() { if (!this.application) throw new Error('Create a draft before continuing'); return this.application.id; }
  private async request<T>(path: string, options: { method?: string; body?: unknown; headers?: Record<string, string>; anonymous?: boolean } = {}): Promise<T> { const headers: Record<string, string> = { 'Content-Type': 'application/json', ...(options.headers ?? {}) }; if (this.token && !options.anonymous) headers.Authorization = `Bearer ${this.token}`; if (this.application && !options.anonymous && headers['If-Match'] === undefined) headers['If-Match'] = String(this.application.version); const retrySlot = (path.endsWith('/transitions') || path.includes('/assessments/')) ? JSON.stringify([path,headers['If-Match'],options.body]) : null; if(retrySlot){const key=this.retryKeys.get(retrySlot)??headers['Idempotency-Key']??('mobile-'+Date.now()+'-'+Math.random()); this.retryKeys.set(retrySlot,key); headers['Idempotency-Key']=key;} const response = await fetch(`${this.config.apiBaseUrl}${path}`, { method: options.method ?? 'GET', headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) }); const contentType = response.headers.get('content-type') ?? ''; const raw = await response.text(); let payload: any = null; if (raw) { if (contentType.includes('application/json')) { try { payload = JSON.parse(raw); } catch { throw new Error(`Server returned invalid JSON (${response.status})`); } } else { throw new Error(`Server returned ${response.status} ${response.statusText || 'an unexpected non-JSON response'}`); } } if (!response.ok) { if(retrySlot && response.status<500)this.retryKeys.delete(retrySlot); throw new Error(payload?.error?.message ?? payload?.message ?? 'GeoCredit request failed'); } if(!payload || !('data' in payload)) throw new Error('Server response is missing data'); if(retrySlot)this.retryKeys.delete(retrySlot); return payload.data as T; }
}
