import { useState } from 'react';
import { View, Text, TextInput, Pressable, StyleSheet } from 'react-native';
import type { AssessmentInput } from '@geocredit/risk-engine';
export type ScoreResult={totalScore:string|null;classification:string;ruleVersion:string;notice:string;categories:Array<{key:string;score:string|null;weightPercent:number;weightedContribution:string|null;reason:string}>};
export type AssessmentBundle={cdo:{result:ScoreResult}|null;bm:{result:ScoreResult}|null;canonical:{role:string;result:ScoreResult}|null;differences:Array<{category:string;cdo:string|null;bm:string|null;difference:string|null}>;legacy:boolean};
const labels:Record<string,string>={incomeSource:'Income Source',socialAcceptance:'Social Acceptance',transactionHistory:'Transaction History',savings:'Savings',houseInfrastructure:'House Infrastructure'};
export function Scores({bundle}:{bundle?:AssessmentBundle}){const result=bundle?.canonical?.result??bundle?.cdo?.result??bundle?.bm?.result;return <View style={s.box}><Text style={s.title}>Client Score · higher is better</Text><Text>AI Recommendation — Human Review Required</Text><View style={s.box}><Text style={s.title}>Client Score: {result?.totalScore??'INCOMPLETE'}</Text><Text>{result?.classification??'INCOMPLETE'} · {result?.ruleVersion??'No versioned assessment'}</Text>{result?.categories.map(category=><Text key={category.key}>{labels[category.key]}: {category.score??'INCOMPLETE'} × {category.weightPercent}% → {category.weightedContribution??'—'}</Text>)}</View><Text>Latest reviewer: {bundle?.canonical?.role??'None'} · {result?.totalScore??'INCOMPLETE'}</Text></View>;}
export function AssessmentPanel({initialIncome,initialExpense,onSave,disabled=false}:{initialIncome:string;initialExpense:string;onSave:(input:AssessmentInput,confirmed:boolean)=>Promise<void>;disabled?:boolean}){
 const [income,setIncome]=useState(initialIncome),[expense,setExpense]=useState(initialExpense),[debt,setDebt]=useState(''),[rating,setRating]=useState('');
 const [stability,setStability]=useState<'STABLE'|'SEASONAL'|'IRREGULAR'>();
 const [structure,setStructure]=useState<'DURABLE'|'SEMI_DURABLE'|'TEMPORARY'>(),[condition,setCondition]=useState<'GOOD'|'FAIR'|'POOR'>(),[utilities,setUtilities]=useState<boolean>(),[confirmed,setConfirmed]=useState(false);
 const [saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const options=(title:string,values:string[],selected:string|undefined,set:(value:any)=>void)=><View style={s.box}><Text>{title}</Text>{values.map(value=><Pressable disabled={disabled||saving} key={value} onPress={()=>set(value)} style={s.button}><Text>{selected===value?'● ':'○ '}{value.replaceAll('_',' ')}</Text></Pressable>)}</View>;
 const field=(title:string,value:string,set:(v:string)=>void)=><View><Text>{title}</Text><TextInput editable={!disabled&&!saving} style={s.input} keyboardType="decimal-pad" value={value} onChangeText={set}/></View>;
 return <View style={s.box}><Text style={s.title}>Scoring assessment · demo-client-v1</Text><Text>Record observed facts. Transaction/savings scores use server records. Missing observations remain incomplete.</Text>{field('Monthly income BDT',income,setIncome)}{field('Monthly expense BDT',expense,setExpense)}{field('Monthly external debt payments BDT (enter 0 if none)',debt,setDebt)}{options('Income stability',['STABLE','SEASONAL','IRREGULAR'],stability,setStability)}{field('Social acceptance rating (1–10)',rating,setRating)}{options('House structure',['DURABLE','SEMI_DURABLE','TEMPORARY'],structure,setStructure)}{options('House condition',['GOOD','FAIR','POOR'],condition,setCondition)}{options('Basic utilities observed',['YES','NO'],utilities===undefined?undefined:utilities?'YES':'NO',value=>setUtilities(value==='YES'))}<Pressable disabled={disabled||saving} onPress={()=>setConfirmed(!confirmed)} style={s.button}><Text>{confirmed?'☑':'☐'} I verified member identity, reviewed house evidence, and confirmed financial information.</Text></Pressable><Pressable disabled={disabled||saving} style={s.button} onPress={async()=>{if(saving)return;setSaving(true);try{await onSave({incomeSource:{monthlyIncome:income||undefined,monthlyExpense:expense||undefined,monthlyDebtPayment:debt||undefined,stability},socialAcceptance:{rating:rating?Number(rating):undefined},houseInfrastructure:{structure,condition,basicUtilities:utilities}},confirmed);setMessage('Saved. Review the score and any incomplete categories before submitting.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed');}finally{setSaving(false);}}}><Text>{saving?'Saving…':'Save assessment and checklist'}</Text></Pressable><Text>{message}</Text></View>;
}
const s=StyleSheet.create({box:{padding:12,marginVertical:10,borderWidth:1,borderColor:'#bfd7cc',borderRadius:12},title:{fontSize:18,fontWeight:'700',marginBottom:8},input:{borderWidth:1,borderColor:'#aaa',padding:10,marginVertical:6,borderRadius:8},button:{padding:12,marginVertical:4,backgroundColor:'#e0eee6',borderRadius:8}});
