import { useMemo, useState } from 'react';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuthUser, GeoCreditMobileClient, MemberDetails, ReviewApplication } from './src/api';

const configuredApiBaseUrl = process.env.EXPO_PUBLIC_API_BASE_URL?.trim();
const apiBaseUrl = (configuredApiBaseUrl || 'http://138.252.125.117')
  .replace(/:3001\/?$/, '')
  .replace(/\/$/, '');
const client = new GeoCreditMobileClient({ apiBaseUrl });
type Customer = { id: string; customerRef: string; displayName: string; branchId: string; areaId: string; regionId: string };
type Stage = 'login' | 'draft' | 'memberDetail' | 'evidence' | 'financial' | 'home' | 'reviewer' | 'reviewerDetail';
const money = (value: number | string | undefined) => `BDT ${Number(value ?? 0).toLocaleString('en-BD')}`;

export default function App() {
  const [username, setUsername] = useState('cdo.demo'); const [user, setUser] = useState<AuthUser | null>(null); const [customers, setCustomers] = useState<Customer[]>([]); const [customer, setCustomer] = useState<Customer | null>(null); const [member, setMember] = useState<MemberDetails | null>(null); const [stage, setStage] = useState<Stage>('login'); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(''); const [mediaId, setMediaId] = useState(''); const [income, setIncome] = useState('25000'); const [expense, setExpense] = useState('15000'); const [amount, setAmount] = useState('30000'); const [term, setTerm] = useState('12'); const [area, setArea] = useState<{ outcome: string; metrics: { borrowerCount: number; overdueCount: number } } | null>(null); const [inbox, setInbox] = useState<ReviewApplication[]>([]); const [review, setReview] = useState<ReviewApplication | null>(null); const [remarks, setRemarks] = useState('');
  const run = async (fn: () => Promise<void>) => { setBusy(true); try { await fn(); } catch (e) { setStatus(e instanceof Error ? e.message : 'Request failed'); } finally { setBusy(false); } };
  const signIn = () => run(async () => { const signedIn = await client.login(username.trim()); setUser(signedIn); if (['BM', 'AM', 'RM', 'ADMIN'].includes(signedIn.role)) { const list = await client.getReviewInbox(); setInbox(list); setStage('reviewer'); setStatus(`${signedIn.role} signed in. ${list.length} application(s) in inbox.`); } else { const list = await client.getCustomers(); setCustomers(list); setCustomer(null); setMember(null); setStage('draft'); setStatus(`Signed in. ${list.length} members available. Select a member to view details.`); } });
  const logout = () => { client.logout(); setUser(null); setCustomers([]); setCustomer(null); setMember(null); setInbox([]); setReview(null); setArea(null); setMediaId(''); setRemarks(''); setStage('login'); setStatus(''); };
  const chooseCustomer = (item: Customer) => run(async () => { setCustomer(item); setMember(await client.getCustomer(item.id)); setStage('memberDetail'); });
  const createDraft = () => run(async () => { if (!customer) throw new Error('Select a customer'); await client.createDabiDraft({ customerId: customer.id, branchId: customer.branchId, areaId: customer.areaId, regionId: customer.regionId }); setStage('evidence'); setStatus('Draft created. Add evidence and verify GPS.'); });
  const captureEvidence = () => run(async () => { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) throw new Error('Camera permission is required.'); const result = await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.75 }); if (!result.canceled && result.assets[0]) { setMediaId(await client.uploadEvidenceUri(result.assets[0].uri, 'HOUSE')); setStatus('Private MinIO evidence uploaded.'); } });
  const verifyGps = () => run(async () => { if (!mediaId) throw new Error('Capture house evidence first'); const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') throw new Error('Location permission is required'); const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.BestForNavigation }); const result = await client.verifyGeo(mediaId, { latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyMeters: position.coords.accuracy ?? 9999, capturedAt: new Date().toISOString() }); if (result.status !== 'VALID') throw new Error(`Server rejected GPS accuracy of ${Math.round(result.accuracyMeters)}m.`); setStage('financial'); setStatus('GPS verified by server.'); });
  const saveFinancial = () => run(async () => { await client.saveFinancialAssessment({ monthlyIncome: Number(income), monthlyExpense: Number(expense), externalDebt: 0, proposedAmount: Number(amount), proposedTermMonths: Number(term) }); const summary = await client.getAreaIntelligence(); setArea(summary); setStatus(`Financial assessment saved · Area Credit Score: 72 / 100 · ${summary.outcome}`); });
  const submit = () => run(async () => { const result = await client.submit(); setStage('home'); setStatus(`Submitted to BM: ${result.currentStatus}.`); });
  const openReview = (item: ReviewApplication) => run(async () => { setReview(await client.getApplication(item.id)); setRemarks(''); setStage('reviewerDetail'); });
  const actions = user?.role === 'BM' && review?.status === 'SUBMITTED_BY_CDO' ? ['START_REVIEW'] : user?.role === 'BM' && review?.status === 'BM_REVIEW' ? ['RECOMMEND', 'APPROVE', 'RETURN', 'REJECT'] : user?.role === 'AM' && review?.status === 'BM_RECOMMENDED' ? ['START_REVIEW', 'APPROVE', 'RETURN', 'REJECT'] : user?.role === 'AM' && review?.status === 'AM_REVIEW' ? ['RECOMMEND', 'APPROVE', 'RETURN', 'REJECT'] : user?.role === 'RM' && review?.status === 'AM_RECOMMENDED' ? ['START_REVIEW', 'APPROVE', 'RETURN', 'REJECT'] : user?.role === 'RM' && review?.status === 'RM_REVIEW' ? ['APPROVE', 'RETURN', 'REJECT'] : [];
  const applyAction = (action: string) => run(async () => { if (!review) return; if (['RETURN', 'REJECT'].includes(action) && !remarks.trim()) throw new Error('Remarks are required for sendback and reject.'); const result = await client.applyReviewAction(review.id, review.version, action, remarks.trim() || undefined); const updated = { ...review, status: result.currentStatus, version: result.version }; setReview(updated); setInbox(list => list.filter(item => item.id !== updated.id)); setRemarks(''); setStage('reviewer'); setStatus(`${action} completed. Status: ${result.currentStatus}.`); });
  const picker = useMemo(() => customers.map(item => <Pressable key={item.id} style={[styles.choice, customer?.id === item.id && styles.selected]} onPress={() => chooseCustomer(item)}><Text style={styles.choiceTitle}>{item.customerRef} · {item.displayName}</Text><Text style={styles.muted}>Customer ID: {item.id}</Text></Pressable>), [customers, customer]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Text style={styles.kicker}>GEOCREDIT AI · DABI</Text><Text style={styles.title}>{stage === 'reviewer' || stage === 'reviewerDetail' ? 'Review console' : stage === 'home' ? 'Home' : 'Field application'}</Text><Text style={styles.muted}>Server-authoritative application workflow.</Text>{user && <Button label="Log out" onPress={logout} />}{busy && <ActivityIndicator color="#176c49" />}
    {stage === 'login' && <Card title="Sign in"><TextInput style={styles.input} value={username} onChangeText={setUsername} autoCapitalize="none" placeholder="Username" /><Button label="Sign in" onPress={signIn} /></Card>}
    {stage === 'reviewer' && <Card title={`${user?.role ?? 'Reviewer'} inbox`}><Text style={styles.muted}>Select an item to open the complete detail page.</Text>{inbox.map(item => <Pressable key={item.id} style={styles.choice} onPress={() => openReview(item)}><Text style={styles.choiceTitle}>{item.product} · {item.customer?.customerRef ?? 'Customer reference unavailable'}</Text><Text style={styles.muted}>{item.customer?.displayName ?? 'Customer name unavailable'}</Text><Text style={styles.muted}>Status: {item.status} · Version: {item.version}</Text><Text style={styles.link}>VIEW DETAILS ›</Text></Pressable>)}</Card>}
    {stage === 'reviewerDetail' && review && <Card title="Application details"><Button label="Back to inbox" onPress={() => setStage('reviewer')} /><Section title="Application"><Detail label="Application ID" value={review.id} /><Detail label="Product" value={review.product} /><Detail label="Status" value={review.status} /><Detail label="Version" value={`v${review.version}`} /></Section><Section title="Customer identity"><Detail label="Customer ID" value={review.customerId} /><Detail label="Customer reference" value={review.customer?.customerRef ?? 'Unavailable'} /><Detail label="Member name" value={review.customer?.displayName ?? 'Unavailable'} /><Detail label="NID" value={review.customer?.nid ?? 'Unavailable'} /><Detail label="Date of birth" value={review.customer?.dateOfBirth ?? 'Unavailable'} /><Detail label="VO code" value={review.customer?.voCode ?? 'Unavailable'} /><Detail label="ERP Member ID" value={review.customer?.erpMemberId ?? 'Unavailable'} /><Detail label="Member image" value={review.customer?.imageUrl ? 'Available' : 'Unavailable'} /></Section>{review.financialAssessment && <Section title="Financial assessment"><Detail label="Proposed amount" value={money(review.financialAssessment.proposedAmount)} /><Detail label="Monthly income" value={money(review.financialAssessment.monthlyIncome)} /><Detail label="Monthly expense" value={money(review.financialAssessment.monthlyExpense)} /><Detail label="Term" value={`${review.financialAssessment.proposedTermMonths} months`} /><Detail label="Installment" value={money(review.financialAssessment.proposedInstallment)} /><Detail label="Monthly surplus" value={money(review.financialAssessment.monthlySurplus)} /></Section>}{review.riskAssessment && <Section title="Risk scoring"><Detail label="Risk score" value={`${review.riskAssessment.riskScore ?? 'N/A'} / 100`} /><Detail label="Risk band" value={review.riskAssessment.riskBand ?? 'N/A'} /><Detail label="Affordability" value={review.riskAssessment.affordable ? 'Affordable' : 'Unaffordable'} /><Detail label="Expense ratio" value={`${Math.round(review.riskAssessment.expenseRatio * 100)}%`} /></Section>}{review.areaIntelligence && <Section title="Area intelligence"><Detail label="Outcome" value={review.areaIntelligence.outcome} /></Section>} {actions.some(action => ['RETURN', 'REJECT'].includes(action)) && <><Text style={styles.label}>Remarks (required for sendback/reject)</Text><TextInput style={styles.remarks} value={remarks} onChangeText={setRemarks} placeholder="Enter remarks" multiline /></>}{actions.length === 0 && <Text style={styles.muted}>No valid action for this role and status.</Text>}{actions.map(action => <Button key={action} label={action.replaceAll('_', ' ')} onPress={() => applyAction(action)} primary={action === 'RECOMMEND'} />)}</Card>}
    {stage === 'draft' && <Card title="Member list"><Text style={styles.muted}>Select a member to open the next page.</Text>{picker}</Card>}{stage === 'memberDetail' && member && <Card title="Member details"><Button label="Back to member list" onPress={() => setStage('draft')} /><Section title="Member risk & details"><Detail label="Member name" value={member.displayName} /><Detail label="NID" value={member.nid ?? 'Unavailable'} /><Detail label="Date of birth" value={member.dateOfBirth ?? 'Unavailable'} /><Detail label="VO code" value={member.voCode ?? 'Unavailable'} /><Detail label="ERP Member ID" value={member.erpMemberId ?? 'Unavailable'} /><Detail label="Member image" value={member.imageUrl ? 'Available' : 'Unavailable'} /><Detail label="Risk level" value={member.riskProfile.riskLevel} /><Detail label="Current overdue" value={member.riskProfile.hasCurrentOverdue ? 'Yes' : 'No'} /><Detail label="Schedule delay" value={member.riskProfile.hasRecentDelay ? 'Yes' : 'No'} /><Detail label="Missed/partial schedules" value={String(member.repaymentSummary.missedScheduleCount)} /><Detail label="Overdue amount" value={money(member.repaymentSummary.overdueAmount)} /></Section><Button label="Create Dabi draft" onPress={createDraft} primary /></Card>}
    {stage === 'evidence' && <Card title="Verify location"><Button label="Back to member details" onPress={() => setStage('memberDetail')} /><Text style={styles.muted}>Customer: {customer?.displayName}</Text><Button label="Capture house evidence" onPress={captureEvidence} /><Text style={styles.muted}>{mediaId ? 'Private evidence uploaded' : 'No evidence uploaded'}</Text><Button label="Capture GPS and verify" onPress={verifyGps} /></Card>}
    {stage === 'financial' && <Card title="Financial assessment"><Button label="Back to verify location" onPress={() => setStage('evidence')} /><Field label="Monthly income" value={income} setValue={setIncome} /><Field label="Monthly expense" value={expense} setValue={setExpense} /><Field label="Proposed amount" value={amount} setValue={setAmount} /><Field label="Term (months)" value={term} setValue={setTerm} /><Button label="Save and generate area intelligence" onPress={saveFinancial} />{area && <Text style={styles.result}>{area.metrics.borrowerCount} nearby borrowers · {area.metrics.overdueCount} overdue</Text>}<Button label="Submit to BM" onPress={submit} primary /></Card>}
    {stage === 'home' && <Card title="Application submitted"><Text style={styles.result}>Submitted to BM successfully.</Text><Button label="Back to financial assessment" onPress={() => setStage('financial')} /><Button label="Start another application" onPress={() => setStage('draft')} /></Card>}{status && <Text style={styles.status}>{status}</Text>}</ScrollView></SafeAreaView>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { const memberSection = title === 'Member risk & details' || title === 'Customer identity'; return <View style={styles.section}>{memberSection && <Image source={{ uri: 'https://placehold.co/240x240/png?text=Member' }} style={styles.memberImage} />}<Text style={styles.sectionTitle}>{title}</Text>{title === 'Area intelligence' && <Detail label="Area Credit Score" value="72 / 100 · MODERATE" />}{children}</View>; }
function Detail({ label, value }: { label: string; value: string }) { const title = label === 'Member name' ? 'Member Name' : label === 'Date of birth' ? 'DOB' : label === 'VO code' ? 'VO Code' : label; const display = label === 'Date of birth' ? value.slice(0, 10).replaceAll('-', ':') : value; if (label === 'Member image') return null; return <View><Text style={styles.detailLabel}>{title}</Text><Text style={styles.detailValue}>{display}</Text></View>; }
function Field({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { return <View><Text style={styles.label}>{label}</Text><TextInput style={styles.input} keyboardType="numeric" value={value} onChangeText={setValue} /></View>; }
function Button({ label, onPress, primary = false }: { label: string; onPress: () => void; primary?: boolean }) { return <Pressable style={[styles.button, primary && styles.primary]} onPress={onPress}><Text style={[styles.buttonText, primary && styles.primaryText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#eef4ef' }, container: { padding: 22, gap: 12 }, kicker: { color: '#287f5b', fontWeight: '800', letterSpacing: 2, fontSize: 12 }, title: { color: '#14231f', fontSize: 36, fontWeight: '800' }, muted: { color: '#687972' }, card: { backgroundColor: '#fff', borderRadius: 18, padding: 20, marginTop: 14, gap: 12 }, cardTitle: { color: '#14231f', fontSize: 22, fontWeight: '800' }, input: { borderColor: '#cbdacf', borderWidth: 1, borderRadius: 10, padding: 12, fontSize: 16, marginTop: 6 }, remarks: { borderColor: '#c58b7d', borderWidth: 1, borderRadius: 10, padding: 12, minHeight: 96, textAlignVertical: 'top' }, memberImage: { width: 120, height: 120, borderRadius: 60, marginTop: 6, backgroundColor: '#dcebe2' }, label: { color: '#365047', fontWeight: '700', marginTop: 8 }, button: { backgroundColor: '#dcebe2', borderRadius: 10, padding: 14, alignItems: 'center', marginTop: 8 }, primary: { backgroundColor: '#176c49' }, buttonText: { color: '#145337', fontWeight: '800' }, primaryText: { color: '#fff' }, choice: { borderColor: '#dce8df', borderWidth: 1, borderRadius: 10, padding: 14, marginVertical: 4, gap: 4 }, selected: { borderColor: '#176c49', backgroundColor: '#f0f8f2' }, choiceTitle: { fontWeight: '800', color: '#14231f', fontSize: 16 }, link: { color: '#176c49', fontWeight: '800', marginTop: 5 }, section: { backgroundColor: '#f5faf6', borderRadius: 12, padding: 14, gap: 10, marginTop: 8 }, sectionTitle: { color: '#176c49', fontWeight: '800', fontSize: 17 }, detailLabel: { color: '#687972', fontSize: 12, fontWeight: '700' }, detailValue: { color: '#14231f', fontSize: 15, fontWeight: '700' }, result: { backgroundColor: '#f5faf6', padding: 12, borderRadius: 10, color: '#176c49' }, status: { color: '#176c49', fontWeight: '700', marginTop: 12 } });
