import { Body, Controller, Headers, HttpException, Post, Param } from '@nestjs/common';
import { Pool } from 'pg';
import { createHash, randomUUID } from 'node:crypto';
import { S3Client, HeadBucketCommand, CreateBucketCommand, PutObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { verifyProductionBearer } from './security';

const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://geocredit:geocredit@127.0.0.1:55432/geocredit' });
const provider = () => process.env.MEDIA_STORAGE_PROVIDER ?? 'minio';
const bucket = () => process.env.MINIO_BUCKET ?? 'geocredit-private';
const endpoint = () => process.env.MINIO_ENDPOINT ?? 'http://127.0.0.1:59000';
const client = (s3Endpoint = endpoint()) => new S3Client({ region: process.env.MINIO_REGION ?? 'us-east-1', endpoint: s3Endpoint, forcePathStyle: true, credentials: { accessKeyId: process.env.MINIO_ROOT_USER ?? 'geocreditminio', secretAccessKey: process.env.MINIO_ROOT_PASSWORD ?? 'geocreditminiosecret' } });
function fail(status: number, code: string, message: string): never { throw new HttpException({ error: { code, message, requestId: randomUUID() } }, status); }
async function user(headers: Record<string, string | undefined>) { const raw = headers.authorization?.replace(/^Bearer\s+/i, ''); if (!raw) fail(401, 'AUTHENTICATION_REQUIRED', 'Valid session required'); let id = ''; try { id = process.env.AUTH_PROVIDER === 'development' && process.env.APP_ENV !== 'production' ? Buffer.from(raw, 'base64url').toString('utf8') : verifyProductionBearer(raw); } catch { fail(401, 'AUTHENTICATION_REQUIRED', 'Invalid or expired session'); } const result = await pool.query('SELECT id,active FROM users WHERE id=$1', [id]); if (!result.rowCount || !result.rows[0].active) fail(401, 'AUTHENTICATION_REQUIRED', 'Active account required'); return result.rows[0]; }
async function ensureBucket(s3: S3Client) { try { await s3.send(new HeadBucketCommand({ Bucket: bucket() })); } catch { await s3.send(new CreateBucketCommand({ Bucket: bucket() })); } }

@Controller()
export class MediaController {
  @Post('api/v1/media/s3-upload-sessions') async create(@Headers() headers: Record<string, string | undefined>, @Body() body: unknown) { const u = await user(headers); if (!['minio', 's3'].includes(provider())) fail(503, 'MEDIA_PROVIDER_NOT_CONFIGURED', 'MinIO/S3 media provider is not enabled'); const mediaType = (body as { mediaType?: string })?.mediaType; if (!['HOUSE', 'BUSINESS', 'DOCUMENT'].includes(mediaType ?? '')) fail(422, 'VALIDATION_ERROR', 'Invalid media type'); const mediaId = randomUUID(); const sessionId = randomUUID(); const uploadToken = Buffer.from(`${sessionId}.${randomUUID()}`).toString('base64url'); const key = `private/${u.id}/${mediaId}`; const ttl = Number(process.env.MEDIA_UPLOAD_TTL_SECONDS ?? 900); const s3 = client(); await ensureBucket(s3); await pool.query('INSERT INTO media_evidence(id,storage_key,media_type,upload_status,created_by) VALUES($1,$2,$3,\'PENDING\',$4)', [mediaId, key, mediaType, u.id]); await pool.query('INSERT INTO media_upload_sessions(id,media_id,token_hash,expires_at,created_by) VALUES($1,$2,$3,now()+($4||\' seconds\')::interval,$5)', [sessionId, mediaId, createHash('sha256').update(uploadToken).digest('hex'), ttl, u.id]); const signingClient = client(process.env.MINIO_PUBLIC_ENDPOINT ?? endpoint()); const uploadUrl = await getSignedUrl(signingClient, new PutObjectCommand({ Bucket: bucket(), Key: key, ContentType: 'application/octet-stream' }), { expiresIn: ttl }); return { data: { mediaId, uploadSessionId: sessionId, uploadToken, uploadUrl, method: 'PUT', requiredHeaders: { 'Content-Type': 'application/octet-stream' }, expiresInSeconds: ttl, bucket: bucket(), private: true } }; }
  @Post('api/v1/media/:id/s3-complete') async complete(@Headers() headers: Record<string, string | undefined>, @Headers('x-upload-token') uploadToken: string | undefined, @Param('id') id: string) { const u = await user(headers); if (!uploadToken) fail(401, 'UPLOAD_TOKEN_REQUIRED', 'Upload token is required'); const result = await pool.query('SELECT s.id,m.storage_key AS "storageKey" FROM media_upload_sessions s JOIN media_evidence m ON m.id=s.media_id WHERE s.media_id=$1 AND s.token_hash=$2 AND s.created_by=$3 AND s.used_at IS NULL AND s.expires_at>now()', [id, createHash('sha256').update(uploadToken).digest('hex'), u.id]); if (!result.rowCount) fail(403, 'UPLOAD_SESSION_INVALID', 'Upload session is invalid or expired'); try { await client().send(new HeadObjectCommand({ Bucket: bucket(), Key: result.rows[0].storageKey })); } catch { fail(422, 'MEDIA_NOT_FOUND', 'Upload was not found in MinIO'); } await pool.query('UPDATE media_evidence SET upload_status=\'UPLOADED\' WHERE id=$1', [id]); await pool.query('UPDATE media_upload_sessions SET used_at=now() WHERE id=$1', [result.rows[0].id]); return { data: { mediaId: id, status: 'UPLOADED', private: true, provider: 'minio' } }; }
}
