import { beforeEach, expect, it, vi } from 'vitest';
// Exercise the actual browser helper, not a duplicated implementation.
// @ts-expect-error Browser source intentionally remains plain JavaScript.
import { request, clearSession } from '../../web/http.js';
function storage(){const values:Record<string,string>={};return new Proxy({getItem:(k:string)=>values[k]??null,setItem:(k:string,v:string)=>{values[k]=v;},removeItem:(k:string)=>{delete values[k];}}, {ownKeys:()=>Object.keys(values),getOwnPropertyDescriptor:()=>({enumerable:true,configurable:true})});}
beforeEach(()=>{vi.stubGlobal('localStorage',storage());vi.stubGlobal('sessionStorage',storage());});
it('serializes objects exactly once',async()=>{const fetch=vi.fn().mockResolvedValue(new Response('{"data":{"ok":true}}'));vi.stubGlobal('fetch',fetch);await request('','token','/api',{method:'POST',body:{action:'SUBMIT'}});expect(fetch.mock.calls[0]?.[1].body).toBe('{"action":"SUBMIT"}');});
it('preserves already serialized JSON',async()=>{const fetch=vi.fn().mockResolvedValue(new Response('{"data":{}}'));vi.stubGlobal('fetch',fetch);await request('','','/api',{body:'{"a":1}'});expect(fetch.mock.calls[0]?.[1].body).toBe('{"a":1}');});
it('handles HTML errors safely',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('<html>Unavailable</html>',{status:503})));await expect(request('','','/api')).rejects.toThrow('503: expected JSON');});
it('retains the transition key after network failure',async()=>{const fetch=vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(new Response('{"data":{}}'));vi.stubGlobal('fetch',fetch);const options={method:'POST',headers:{'If-Match':'2'},body:{action:'START_REVIEW'}};await expect(request('','','/app/transitions',options)).rejects.toThrow('offline');await request('','','/app/transitions',options);expect(fetch.mock.calls[0]?.[1].headers.get('Idempotency-Key')).toBe(fetch.mock.calls[1]?.[1].headers.get('Idempotency-Key'));});
it('clears only application session keys',()=>{localStorage.setItem('geocredit.token','secret');sessionStorage.setItem('geocredit.retry.test','key');localStorage.setItem('unrelated','keep');clearSession();expect(localStorage.getItem('geocredit.token')).toBeNull();expect(sessionStorage.getItem('geocredit.retry.test')).toBeNull();expect(localStorage.getItem('unrelated')).toBe('keep');});
